### ISSUE TITLE
Avoir une méthode pour la météo du jour et celle des 8 prochains jours

### ISSUE THREAD

**Issue by P0ppoff** [Zenika/grenoble-hands-on-vuejs#14]
On pourrait changer le fichier d'API pour avoir deux méthodes qui font le même appel mais une qui renvoie seulement le premier jour et une qui renvoie la liste complète. Je trouve que ça serait plus juste par rapport aux instructions 
> Via le service d'API récupérer maintenant la météo des 8 prochains jours

**Comment by thuchede** [comment]
D'ailleurs il faudrait peut-être revoir l'instruction en question car l'API renvoie 7 jours et non pas 8 (et inclus la date du jour d'ailleurs).
